### ISSUE TITLE
Integrate parts

### ISSUE THREAD

**Issue by osclind** [DD2480-group18/dd2480-g18-Continuous-Integration#34]
Now we need to put the parts together and make sure that the system does what it is supposed to:

1. Handle the post request from GitHub correctly:
 -   [x]  Send a "pending" status during the build
 -   [x]  Send "success" or "failure"/"error" status upon completion
 -   [x]  Save the logs from our test run into the database and a file 
2. Display the history (with satisfactory detail) on the allBuilds endpoint
3. Display detailed build information on the build endpoint

**Comment by osclind** [comment]
Found bugs in tests:
- Tests not reading/writing from cloudbuilds
- branch with data in testdatacommit.json is missing on git, replace with data from test branch

**Comment by martinfalke** [comment]
As of eec7e02 the maven script (local and Travis) throws a FileNotFoundException, this should be resolved in the jsonHandlerTest code before #43 can be merged into main.
