### ISSUE TITLE
Adding Javadoc 

### ISSUE THREAD

**Issue by davyie** [DD2480-group18/dd2480-g18-Continuous-Integration#38]
This issue regards solving the missing documentations in code

**Comment by martinfalke** [comment]
Final functions missing javadoc TODO (everyone should be able to check the boxes):
- [x] Constructors in jsonhandler
- [x] Constructors in build
- [x] equals in build
- [x] Constructors in build history
- [x] get next build id build history
- [x] handle in ContinuousIntegrationServer
- [x] constructor in ContinuousIntegrationServer
- [x] prettyprint in ContinuousIntegrationServer
- [x] fourofour in ContinuousIntegrationServer

**Comment by martinfalke** [comment]
Resolved as of #57
